### PR TITLE
OCPBUGS-30122: Bump openshift/prometheus-operator to v0.77.1

### PR DESCRIPTION
**Pull request by slashpai**
Downgraded to go 1.22 as OCP 4.18 is on 1.22
supersedes #306 #310

### CODE REVIEW

**Comment by slashpai** [comment]
cc @simonpasquier

**Comment by simonpasquier** [comment]
/hold
the failure is legit.

**Comment by simonpasquier** [comment]
/retitle OCPBUGS-30122: Bump openshift/prometheus-operator to v0.77.1

**Comment by slashpai** [comment]
cc @simonpasquier

**Pull request merged**
