### PR TITLE
Sync with upstream

### PR DESCRIPTION
**Pull request by LiliC**
cc @brancz @s-urbaniak @paulfantom 

Lets give this another try :)

### CODE REVIEW

**Comment by s-urbaniak** [comment]
/lgtm
:crossed_fingers:

**Comment by LiliC** [comment]
This seems like a flake 🤷‍♀

**Comment by LiliC** [comment]
FYI @pgier your changes have been merged to openshift, so you can now enable the `ignoreNamespaceSelectors` in cluster-monitoring-operator for user workloads.

**Pull request merged**
