### PR TITLE
Bump to 0.47.1

### PR DESCRIPTION
**Pull request by paulfantom**
Reverts #118 to bring in 0.47.0 and updates to 0.47.1

**Release Note Template (will be copied)**

```release-note:REPLACEME

```

### CODE REVIEW

**Comment by paulfantom** [comment]
Verified manually by launching a cluster. The following things were checked:
- only alerts that are expected to be firing were firing
- prometheus and alertmanager were accesible
- all panels in grafana were having data
- All scrape jobs from openshift-monitoring namespace were present and working

**Comment by simonpasquier** [comment]
/lgtm
thanks @paulfantom

**Comment by paulfantom** [comment]
Seems that with updating prometheus-operator, collecting metrics from `*-csi-driver-controller-metrics` seems to be broken. Target reports 500.

**Comment by paulfantom** [comment]
Seems like there is something weirdly wrong with this PR. I opened #120 to do the same as here and that one looks like it is working.

**Pull request closed without merging**
