### PR TITLE
Sync with master

### PR DESCRIPTION
**Pull request by LiliC**
cc @brancz @s-urbaniak @paulfantom

### CODE REVIEW

**Comment by s-urbaniak** [comment]
oops, I think we have broken upstream:
```
level=error ts=2019-10-22T07:42:41.719Z caller=main.go:731 err="error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml\": couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: relabel configuration for replace action requires 'target_label' value"
```

**Comment by LiliC** [comment]
Closing and will sync with upstream including the fix in another PR.

**Pull request closed without merging**
