### PR TITLE
Bug 1805834: Tighten permissions related to CRD create/update

### PR DESCRIPTION
**Pull request by pgier**
Backport of https://github.com/coreos/prometheus-operator/pull/2974

### CODE REVIEW

**Comment by lilic** [comment]
> tide Pending — Not mergeable. Merging to branch release-3.11 is forbidden.

huh 🤔

**Comment by s-urbaniak** [comment]
ping @bparees can you help here, we cannot merge here? :shrug:

**Comment by bparees** [comment]
@s-urbaniak must be a tide config thing, check with dpp-helpdesk, guessing the config for this repo is wrong.

**Comment by bparees** [comment]
err, dptp-helpdesk

**Comment by paulfantom** [comment]
@bparees it is 3.11, tide is not enabled for those branches. AFAIK all merging is manual in 3.11.

@brancz are you able to merge it manually?

**Comment by bparees** [comment]
it's enabled for other repos, there's no reason we couldn't enable it for this one

**Pull request merged**
