### PR TITLE
Bug 1832124: retain pvc metdata

### PR DESCRIPTION
**Pull request by pgier**
Backport of upstream PVC metadata fix: https://github.com/coreos/prometheus-operator/pull/3115

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@pgier the upgrade test failure seems to be legit:
```
    <*errors.errorString | 0xc001a6c0c0>: {
        s: "Cluster did not complete upgrade: timed out waiting for the condition: Cluster operator monitoring is still updating",
    }
    Cluster did not complete upgrade: timed out waiting for the condition: Cluster operator monitoring is still updating
```

with an underlying error:
```
May 08 18:20:47.407 E ns/openshift-monitoring pod/prometheus-k8s-1 node/ip-10-0-137-167.ec2.internal container=prometheus-config-reloader container exited with code 2 (Error): ts=2020-05-08T18:19:42.391007353Z caller=main.go:85 msg="Starting prometheus-config-reloader version '1.12.16'."\nlevel=info ts=2020-05-08T18:19:42.391133303Z caller=reloader.go:127 msg="started watching config file for changes" in=/etc/prometheus/config/prometheus.yaml.gz out=/etc/prometheus/config_out/prometheus.env.yaml\nlevel=error ts=2020-05-08T18:19:42.392521749Z caller=runutil.go:87 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post http://localhost:9090/-/reload: dial tcp [::1]:9090: connect: connection refused"\nlevel=error ts=2020-05-08T18:19:47.392715916Z caller=runutil.go:87 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post http://localhost:9090/-/reload: dial tcp [::1]:9090: connect: connection refused"\nlevel=info ts=2020-05-08T18:19:52.504768465Z caller=reloader.go:258 msg="Prometheus reload triggered" cfg_in=/etc/prometheus/config/prometheus.yaml.gz cfg_out=/etc/prometheus/config_out/prometheus.env.yaml rule_dirs=\n
```

**Comment by lilic** [comment]
I would prefer this bugfix merged into the release branch of prom-operator upstream as we are not the only ones impacted by this and then brought in downstream to openshift.

**Comment by pgier** [comment]
Upstream PR to 0.38 release branch https://github.com/coreos/prometheus-operator/pull/3209

**Comment by pgier** [comment]
@s-urbaniak I think it was just a flake, looks like it's passing now.  @lilic I created an upstream PR, but I'm having trouble getting it to build correctly for some reason.

**Comment by pgier** [comment]
@s-urbaniak @lilic is this ok to merge now that the upstream issue is merged?  or do we need an upstream Z release?

**Comment by s-urbaniak** [comment]
my 2 cent: if the content of the cherry-picks is the same as upstream i am fine with merging this. since the QA phase for 4.5 is not over yet we might encounter additional necessary fixes. Once 4.5 code freezes we can cut a z-release upstream.

**Pull request merged**
