### PR TITLE
OCPBUGS-38174: feat: sync proxy settings in Alertmanager configuration

### PR DESCRIPTION
**Pull request by simonpasquier**
Cherry-pick of https://github.com/prometheus-operator/prometheus-operator/pull/6818

### CODE REVIEW

**Comment by machine424** [comment]
We'll need a test for that I think.
I can help with that.
/lgtm

**Comment by simonpasquier** [comment]
A test where?

**Comment by simonpasquier** [comment]
There will be an indirect test with https://github.com/openshift/cluster-monitoring-operator/pull/2431 which is how I found the gap.

**Comment by machine424** [comment]
> There will be an indirect test with [openshift/cluster-monitoring-operator#2431](https://github.com/openshift/cluster-monitoring-operator/pull/2431) which is how I found the gap.

I was thinking about a more direct one in prom-operator (for regression). Because for https://github.com/openshift/cluster-monitoring-operator/pull/2431's tests failures, at first glance, I didn't realize that the AM failures were due to a misconfiguration... (I wasn't looking at the right logs tough, but it wasn't that obvious.)

**Comment by machine424** [comment]
(I'm not trying block https://github.com/openshift/cluster-monitoring-operator/pull/2431 btw)

**Pull request merged**
