### PR TITLE
Bug 1763098: *: Ensure containers have "FallbackToLogsOnError" termination policy

### PR DESCRIPTION
**Pull request by brancz**
This still needs to be verified on master, but here the cherrypick already.

@s-urbaniak @paulfantom @LiliC @pgier @simonpasquier @krasi-georgiev

### CODE REVIEW

**Comment by LiliC** [comment]
Why not bring this change into master as well?

**Comment by brancz** [comment]
Just haven’t yet.

**Comment by s-urbaniak** [comment]
fyi, i'll shepherd the cherry-pick on master, then the backports

**Comment by s-urbaniak** [comment]
ok this is already present in both 4.3 and 4.4, just not in 4.2:
```
$ git branch -av  --contains 395c1df715a196721cd2c1e93071593328f7e6ba | grep release
  release-0.34                                    8d44e099 Merge pull request #2844 from s-urbaniak/release-0.34
  remotes/openshift/release-4.3                   6ba21de5 Merge pull request #46 from coreos/master
  remotes/openshift/release-4.4                   d186e62c Merge pull request #51 from pgier/bump-to-0.35.0
  remotes/openshift/release-4.5                   d186e62c Merge pull request #51 from pgier/bump-to-0.35.0
```

Hence this is good to go.

**Pull request merged**
