### PR TITLE
WIP Bug 1858991: pkg/listwatch: remove multilistwatcher

### PR DESCRIPTION
**Pull request by s-urbaniak**
Note: this is a work-in-progress PR to assert if this works correctly in our environment.

/hold

### CODE REVIEW

**Comment by lilic** [comment]
Retest will not help, you need to write

/test ci/prow/e2e-aws

**Comment by s-urbaniak** [comment]
using manual testing so far i found one issue in the log files with this approach:

```
level=warn ts=2020-08-13T07:17:11.239085731Z caller=allowdenylist_listerwatcher.go:178 component=prometheusoperator msg="unexpected object type in event (*v1.Status): &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:Failure,Message:too old resource version: 41720 (42338),Reason:Expired,Details:nil,Code:410,}"
level=warn ts=2020-08-13T07:17:11.247393465Z caller=allowdenylist_listerwatcher.go:178 component=prometheusoperator msg="unexpected object type in event (*v1.Status): &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:Failure,Message:too old resource version: 41720 (42338),Reason:Expired,Details:nil,Code:410,}"
W0813 07:17:11.247543       1 reflector.go:404] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:480: watch of *v1.PrometheusRule ended with: very short watch: github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:480: Unexpected watch close - watch lasted less than a second and no items received
level=warn ts=2020-08-13T07:17:11.267835115Z caller=allowdenylist_listerwatcher.go:178 component=prometheusoperator msg="unexpected object type in event (*v1.Status): &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:Failure,Message:too old resource version: 41718 (42339),Reason:Expired,Details:nil,Code:410,}"
level=warn ts=2020-08-13T07:17:11.26972669Z caller=allowdenylist_listerwatcher.go:178 component=prometheusoperator msg="unexpected object type in event (*v1.Status): &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:Failure,Message:too old resource version: 41718 (42339),Reason:Expired,Details:nil,Code:410,}"
W0813 07:17:11.269813       1 reflector.go:404] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:478: watch of *v1.ServiceMonitor ended with: very short watch: github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:478: Unexpected watch close - watch lasted less than a second and no items received
level=warn ts=2020-08-13T07:17:11.313860995Z caller=allowdenylist_listerwatcher.go:178 component=thanosoperator msg="unexpected object type in event (*v1.Status): &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:Failure,Message:too old resource version: 41720 (42338),Reason:Expired,Details:nil,Code:410,}"
level=warn ts=2020-08-13T07:17:11.31446867Z caller=allowdenylist_listerwatcher.go:178 component=prometheusoperator msg="unexpected object type in event (*v1.Status): &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:Failure,Message:too old resource version: 30297 (42339),Reason:Expired,Details:nil,Code:410,}"
level=warn ts=2020-08-13T07:17:11.315931499Z caller=allowdenylist_listerwatcher.go:178 component=thanosoperator msg="unexpected object type in event (*v1.Status): &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:Failure,Message:too old resource version: 41720 (42338),Reason:Expired,Details:nil,Code:410,}"
level=warn ts=2020-08-13T07:17:11.316815568Z caller=allowdenylist_listerwatcher.go:178 component=prometheusoperator msg="unexpected object type in event (*v1.Status): &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:Failure,Message:too old resource version: 30297 (42339),Reason:Expired,Details:nil,Code:410,}"
W0813 07:17:11.316023       1 reflector.go:404] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:313: watch of *v1.PrometheusRule ended with: very short watch: github.com/coreos/prometheus-operator/pkg/thanos/operator.go:313: Unexpected watch close - watch lasted less than a second and no items received
W0813 07:17:11.316866       1 reflector.go:404] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:479: watch of *v1.PodMonitor ended with: very short watch: github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:479: Unexpected watch close - watch lasted less than a second and no items received
```

This doesn't seem to cause functionality degradation (famous last words) but it turns out that filtering the list/watch stream manually doesn't work for all objects as some of them (i.e. the above `*v1.Status` object) is not namespaced.

**Comment by s-urbaniak** [comment]
Closing out as e2e tests also are showing the above mentioned log output messages:

```
level=warn ts=2020-08-13T06:12:08.039071299Z caller=allowdenylist_listerwatcher.go:178 component=prometheusoperator msg="unexpected object type in event (*v1.Status): &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:Failure,Message:too old resource version: 45896 (47101),Reason:Expired,Details:nil,Code:410,}"
```

**Pull request closed without merging**
