### PR TITLE
Bug 1845561: use a single reloader for Prometheus

### PR DESCRIPTION
**Pull request by simonpasquier**
Cherry-pick of https://github.com/prometheus-operator/prometheus-operator/pull/3457.

This needs https://github.com/openshift/cluster-monitoring-operator/pull/938 to be merged first.

### CODE REVIEW

**Comment by lilic** [comment]
Just curious how severe is the bug, could we wait until the above lands in the next release instead so we don't carry patches?

**Comment by simonpasquier** [comment]
Oops I've used the wrong Bugzilla ID, the correct one is [1845561](https://bugzilla.redhat.com/show_bug.cgi?id=1845561) which has a high severity because affecting OSD clusters.

**Comment by simonpasquier** [comment]
/hold
https://github.com/openshift/cluster-monitoring-operator/pull/938 not merged yet

**Comment by simonpasquier** [comment]
cc @s-urbaniak

**Pull request merged**
