### PR TITLE
Bump to v0.50.0

### PR DESCRIPTION
**Pull request by jan--f**
**Release Note Template (will be copied)**

```release-note:REPLACEME

```

### CODE REVIEW

**Comment by jan--f** [comment]
`thanos-sidecar` is not coming up and prevents the `prometheus-k8s-*` pods from becoming ready.
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_prometheus-operator/133/pull-ci-openshift-prometheus-operator-master-e2e-agnostic-cmo/1428680803662958592/artifacts/e2e-agnostic-cmo/gather-extra/artifacts/pods/openshift-monitoring_prometheus-k8s-0_thanos-sidecar.log

**Comment by jan--f** [comment]
/hold
Lets postpone this until 4.10 unless we have a bug report that requires p-o 0.50.0

**Comment by dgrisonnet** [comment]
Unholding since 4.10 development branch is now open. We will need to open a follow-up PR to update the labels in CMO. cc @slashpai 

/unhold

**Comment by slashpai** [comment]
Ya I can create PR once this is merged

**Comment by jan--f** [comment]
This needs a fix in CMO before the tests will pass. See https://bugzilla.redhat.com/show_bug.cgi?id=1997028 for details, I'm testing a fix right now and will push a PR soon.

**Comment by jan--f** [comment]
/hold
Wait for https://github.com/openshift/cluster-monitoring-operator/pull/1367

**Pull request merged**
