### PR TITLE
MON-1302: Bump prometheus-operator to v0.44.1

### PR DESCRIPTION
**Pull request by dgrisonnet**
Bump prometheus-operator to v0.44.1.

### CODE REVIEW

**Comment by dgrisonnet** [comment]
Holding until CMO's jsonnet dependencies pinning.

/hold

**Comment by lilic** [comment]
Does this still need a hold?

/retest

**Comment by dgrisonnet** [comment]
I don't think so, CRDs didn't change between v0.44.0 and v0.44.1.

/unhold

**Pull request merged**
