### PR TITLE
Bug 1891815: Revert "Bug 1881077:go.sum,go.mod: Bump client-go & co. to fix known bug"

### PR DESCRIPTION
**Pull request by s-urbaniak**
This reverts openshift/prometheus-operator#95. A follow-up PR in cluster-monitoring-operator will be issued to add suggested alerts.

/cc @openshift/openshift-team-monitoring

### CODE REVIEW

**Comment by s-urbaniak** [comment]
cc'ing @juzhao to verify QE first.

**Comment by juzhao** [comment]
tested with cluster-bot
`launch openshift/prometheus-operator#99 aws`, there's not invalid syntax error
# oc -n openshift-monitoring logs $(oc -n openshift-monitoring get po | grep prometheus-operator | awk '{print $1}') -c prometheus-operator | grep "invalid syntax" | head -n 3
no result

**Pull request merged**
