### PR TITLE
Set preserve unknown fields false

### PR DESCRIPTION
**Pull request by pgier**
This is a backport of the CRD generation and validation PRs

https://github.com/coreos/prometheus-operator/pull/2855
https://github.com/coreos/prometheus-operator/pull/2885
https://github.com/coreos/prometheus-operator/pull/2903

### CODE REVIEW

**Comment by s-urbaniak** [comment]
as discussed OOB: let's explicitly test the upgrade path using cluster-bot and assert that preserveUnknownFields is set to false after upgrade.

Additional idea: does it make sense to verify this field is set in some e2e test? :thinking:

**Comment by pgier** [comment]
Link to upgrade test job: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade-4.3/1

**Comment by pgier** [comment]
This should fix the generated CRDs: https://github.com/coreos/prometheus-operator/pull/2906

**Comment by pgier** [comment]
/hold cancel
The test and fixes have been merged upstream, so I think this is good to go now.

**Pull request merged**
