### PR TITLE
Bug 1806541: Revert of Bug 1853007: Revert of revert: Bump prometheus-operator to v0.40.0

### PR DESCRIPTION
**Pull request by lilic**
This reverts the revert of the 0.40 revert.

**Essentially this bumps the version of prometheus-operator to 0.40.0** again.

cc @openshift/openshift-team-monitoring

### CODE REVIEW

**Comment by lilic** [comment]
Failure is unrelated, but it seems like prom-operator is still logging the errors:
> E0710 08:26:47.467026       1 reflector.go:382] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:299: Failed to watch *v1.PrometheusRule: expected resource version to have 38 parts to match the number of ListerWatchers
E0710 08:26:52.477311       1 reflector.go:382] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:468: Failed to watch *v1.PrometheusRule: expected resource version to have 38 parts to match the number of ListerWatchers
E0710 08:27:11.469882       1 reflector.go:382] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:466: Failed to watch *v1.ServiceMonitor: expected resource version to have 38 parts to match the number of ListerWatchers
E0710 08:28:15.161911       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:467: Failed to list *v1.PodMonitor: resourceVersion: Invalid value: "17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388": strconv.ParseUint: parsing "17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388": invalid syntax
E0710 08:28:17.150357       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:467: Failed to list *v1.PodMonitor: resourceVersion: Invalid value: "17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388": strconv.ParseUint: parsing "17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388/17388": invalid syntax

**Comment by lilic** [comment]
/retest

random failure

**Comment by simonpasquier** [comment]
Hmm, `e2e-aws` fails for Prometheus related tests which isn't good :-/
It looks like no alert fired during the test...

**Comment by simonpasquier** [comment]
From https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_prometheus-operator/80/pull-ci-openshift-prometheus-operator-master-e2e-aws/1283084041825816576/artifacts/e2e-aws/gather-extra/pods/openshift-monitoring_prometheus-operator-5b5b568cc8-fzvst_prometheus-operator.log

```
E0714 18:21:20.442536       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:480: Failed to list *v1.PrometheusRule: resourceVersion: Invalid value: "20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745": strconv.ParseUint: parsing "20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745/20745": invalid syntax
```

The Prometheus data dump shows that only 6 rule groups are configured but we should have more...
image

**Comment by lilic** [comment]
/retest

it was green before, lets see https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-prometheus-operator-master-e2e-aws

**Comment by lilic** [comment]
/hold

Until https://github.com/openshift/cluster-monitoring-operator/pull/850 is merged we can then retest this PR to make sure there are no error msgs in the logs.

**Comment by lilic** [comment]
@openshift/openshift-team-monitoring PTAL, I could not do a clean commits, as due the before-mentioned reasons around revert.

This essentially gets us to the same state as release-0.40 branch is at on prometheus operator upstream.

**Comment by lilic** [comment]
/hold cancel
🤦‍♀️

**Pull request merged**
