### PR TITLE
Bug 1885244: bump to v0.43.0

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Comment by simonpasquier** [comment]
/hold

prometheus-operator fails to deploy Alertmanager as expected because the `AlertmanagerConfig` CRD is missing. We need https://github.com/openshift/cluster-monitoring-operator/pull/970 first.

```
E1027 17:39:35.368845       1 reflector.go:127] github.com/coreos/prometheus-operator/pkg/informers/informers.go:75: Failed to watch *v1alpha1.AlertmanagerConfig: failed to list *v1alpha1.AlertmanagerConfig: alertmanagerconfigs.monitoring.coreos.com is forbidden: User "system:serviceaccount:openshift-monitoring:prometheus-operator" cannot list resource "alertmanagerconfigs" in API group "monitoring.coreos.com" in the namespace "openshift-authentication-operator"
```

**Comment by lilic** [comment]
> level=error msg=Cluster operator monitoring Degraded is True with UpdatingAlertmanagerFailed: Failed to rollout the stack. Error: running task Updating Alertmanager failed: waiting for Alertmanager object changes failed: waiting for Alertmanager openshift-monitoring/main: retrieving Alertmanager status failed: retrieving stateful set failed: statefulsets.apps "alertmanager-main" not found

🤔

**Comment by simonpasquier** [comment]
We need https://github.com/openshift/cluster-monitoring-operator/pull/976 because https://github.com/openshift/cluster-monitoring-operator/pull/970 was incomplete wrt permissions granted to the `prometheus-operator` service account.

**Pull request merged**
