### PR TITLE
MON-3793: Bump openshift/prometheus-operator to v0.73.0 

### PR DESCRIPTION
**Pull request by slashpai**
supersedes #283

### CODE REVIEW

**Comment by danielmellado** [comment]
Hi o/ I assume this is still a WIP. I've seen that there's a few unit tests whose value have changed i.e

```
=== RUN   TestServiceMonitorWithDefaultScrapeClassRelabelings
    promcfg_test.go:8290: assertion failed: 
        --- expected
        +++ actual
        @@ -64,6 +64,6 @@
             replacement: web
           - source_labels:
        -    - __meta_kubernetes_pod_app_name
        -    target_label: app
        +    - __meta_kubernetes_pod_node_name
        +    target_label: node
             action: replace
           - source_labels:
        
        
        You can run 'go test . -update' to automatically update testdata/serviceMonitorObjectWithDefaultScrapeClassWithRelabelings.golden to the new expected value.'
        
--- FAIL: TestServiceMonitorWithDefaultScrapeClassRelabelings (0.00s)
```

**Comment by slashpai** [comment]
Right thats a issue go 1.21 https://go.dev/doc/go1.22#language in for lop. I added a temporary fix to set `GOEXPERIMENT=loopvar` till we move to 1.22 in OCP. Upstream PO uses 1.22 so we didn't see this problem there

We should revert this change once bumped to 1.22

**Comment by danielmellado** [comment]
oh, sigh! didn't realize upstream was in go1.22 and then we had the for loop issue which totally messes the golden files every now and then... /lgtm once this runs, thanks jp!

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Pull request merged**
