### PR TITLE
OCPBUGS-7458: Fixes ThanoRuler StatefulSet re-creation bug

### PR DESCRIPTION
**Pull request by JoaoBraveCoding**
## Description

Issue: https://issues.redhat.com/browse/OCPBUGS-7458

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note

```

### CODE REVIEW

**Comment by jan--f** [comment]
/lgtm
We'll need a bug for the fix on master.

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by JoaoBraveCoding** [comment]
>  We'll need a bug for the fix on master.

@jan--f it was already fixed on https://github.com/openshift/prometheus-operator/pull/216

**Comment by simonpasquier** [comment]
I've created the link between OCPBUGS-6055 and OCPBUGS-7458

**Pull request merged**
