### PR TITLE
Update prometheus-operator to 0.39.0

### PR DESCRIPTION
**Pull request by paulfantom**
Synced by merging `upstream/release-0.39` into `downstream/master`.

/cc @openshift/openshift-team-monitoring

### CODE REVIEW

**Comment by lilic** [comment]
> previous declaration at pkg/apis/monitoring/v1/zz_generated.deepcopy.go:327:6
pkg/apis/monitoring/v1/zz_generated.deepcopy.go:384:42: (*...dedPersistentVolumeClaim).DeepCopy redeclared in this block
	previous declaration at pkg/apis/monitoring/v1/zz_generated.deepcopy.go:336:6
make: *** [operator-no-deps] Error 2


Seems like a valid failure? Maybe just a rebase that went wrong?

**Comment by lilic** [comment]
/hold

> luster: Multiple errors are preventing progress:\n* Could not update prometheusrule \"openshift-cluster-samples-operator/samples-operator-alerts\" (305 of 591): the server does not recognize this resource, check extension API servers\n* Could not update prometheusrule \"openshift-image-registry/image-registry-operator-alerts\" (256 of 591): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-authentication-operator/authentication-operator\" (505 of 591): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-cloud-credential-operator/cloud-credential-operator\" (499 of 591): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-cluster-machine-approver/cluster-machine-approver\" (515 of 591): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-cluster-version/cluster-version-operator\" (8 of 591): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-config-operator/config-operator\" (113 of 591): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-image-registry/image-registry\" (511 of 591): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-insights/insights-operator\" (411 of 591): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-machine-api/cluster-autoscaler-operator\" (220 of 591): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-marketplace/marketplace-operator\" (446 of 591): the server does not recognize this resource, check extension API servers"

Interesting, maybe we need to merge the CMO PR first @paulfantom ?

**Comment by paulfantom** [comment]
> Interesting, maybe we need to merge the CMO PR first

Yes, we need CRD management in CMO before migrating to prom-op 0.39

**Comment by s-urbaniak** [comment]
closing in favor of #77

**Pull request closed without merging**
