### PR TITLE
pkg/prometheus: watch configmaps having the prometheus-name selector

### PR DESCRIPTION
**Pull request by s-urbaniak**
cherry-pick of https://github.com/coreos/prometheus-operator/pull/2454

/cc @brancz @mxinden @metalmatze @squat

### CODE REVIEW

**Comment by s-urbaniak** [comment]
/hold

testing locally first

**Comment by s-urbaniak** [comment]
This seems to work nicely, low idle usage confirmed locally:
```
$ kubectl -n openshift-monitoring top pod
NAME                                   CPU(cores)   MEMORY(bytes)
...
prometheus-operator-744d66dbdc-8zn6t   4m           23Mi
```

Also verified Grafana and Prometheus targets.

**Comment by brancz** [comment]
Thanks for taking care of this!

/lgtm

**Pull request merged**
