### PR TITLE
[release-4.14] OCPBUGS-20881: fix: disable HTTP2 connections by default

### PR DESCRIPTION
**Pull request by slashpai**
cherry-picked from upstream prometheus-operator

### CODE REVIEW

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Review by raptorsun — APPROVED** [review]

**Comment by slashpai** [comment]
/hold
Till OCPBUGS-22946 is evaluated

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by slashpai** [comment]
/hold cancel
verified on 4.15 cluster fix is working

**Pull request merged**
