### PR TITLE
Bug 1893798: MON-1302: Bump prometheus-operator to v0.44.0

### PR DESCRIPTION
**Pull request by dgrisonnet**
Update prometheus-operator downstream fork to the latest upstream release for the OpenShift 4.7 feature freeze checklist.

### CODE REVIEW

**Comment by lilic** [comment]
For this we need the PR in CMO first, as there we create the CRDs.

/hold

**Comment by simonpasquier** [comment]
/title Bug 1893798: MON-1302: Bump prometheus-operator to v0.44.0

**Comment by simonpasquier** [comment]
/retitle Bug 1893798: MON-1302: Bump prometheus-operator to v0.44.0

**Comment by dgrisonnet** [comment]
Unholding as the bump in CMO was merged: https://github.com/openshift/cluster-monitoring-operator/pull/1013

/unhold

**Pull request merged**
