### PR TITLE
Bug 1879047: bump to prometheus-operator 0.42

### PR DESCRIPTION
**Pull request by s-urbaniak**
I believe, before we can merge here, we have to update the CRD definitions in cluster-monitoring-operator first.

/hold
/cc @openshift/openshift-team-monitoring

### CODE REVIEW

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by s-urbaniak** [comment]
As expected e2e failed with rolling out prometheus-operator, we need to merge https://github.com/openshift/cluster-monitoring-operator/pull/928 first.

**Pull request merged**
