### PR TITLE
Bug 1833427: retain pvc metadata

### PR DESCRIPTION
**Pull request by pgier**
Backport of upstream PVC metadata fix: coreos#3115

### CODE REVIEW

**Comment by pgier** [comment]
Upstream backport PR https://github.com/coreos/prometheus-operator/pull/3219

**Comment by lilic** [comment]
Do you not need kube-prometheus for those branches to be updated as well and bumped in CMO?

**Comment by pgier** [comment]
@lilic This is only modifying the CRDs, which cluster-monitoring-operator only uses indirectly via prometheus operator, so I don't think this should need any additional update in CMO/kube-prometheus.  Although it might be worth updating those upstream just for good measure.

**Comment by pgier** [comment]
@lilic While looking into updating kube-prometheus upstream, I noticed that CMO release-4.4 is pointing to prometheus-operator v0.35 and kube-prometheus v0.4, which seems fine, but kube-prometheus v0.4 is actually pointing to prometheus-operator v0.34, so it seems to be one version behind.  I'm wondering if we should fix that, or is it too risky at this point.

**Comment by lilic** [comment]
@pgier Lets find out why we did the bump in that release version in kube-prom, maybe we forgot some bump? 🤔

**Comment by pgier** [comment]
The update to CMO was done here: https://github.com/openshift/cluster-monitoring-operator/pull/624
But I think there was never a similar update to kube-prometheus on the 0.4 branch.
I created a new PR for this: https://github.com/coreos/kube-prometheus/pull/536
I guess it's relatively safe to merge since we already have a v0.4.0 tag and we can always revert if it causes problems.

**Pull request merged**
