### PR TITLE
Release 0.52

### PR DESCRIPTION
**Pull request by raptorsun**
## Description

Update this fork to upstream version 0.52.1.

### CODE REVIEW

**Comment by raptorsun** [comment]
Prometheus v0.52 is required by this PR: https://github.com/openshift/cluster-monitoring-operator/pull/1468

**Comment by simonpasquier** [comment]
you need to update the `vendor` directory (e.g. run `go mod vendor` and commit the changes).

**Comment by raptorsun** [comment]
rhel-8-golang-1.17-openshift-4.10 image is not available yet.

**Comment by raptorsun** [comment]
regenerated with go 1.16. 
we no longer need to wait rhel-8-golang-1.17-openshift-4.10 image now :)

**Comment by PhilipGough** [comment]
> rhel-8-golang-1.17-openshift-4.10 image is not available yet.

https://github.com/openshift/node_exporter/pull/97/files seems to be building with `rhel-8-release-golang-1.17-openshift-4.10`

**Comment by simonpasquier** [comment]
`TestUserWorkloadMonitoringAlerting/assert_tenancy_model_is_enforced_for_rules` fails which would need investigation.

/hold

**Comment by raptorsun** [comment]
> `TestUserWorkloadMonitoringAlerting/assert_tenancy_model_is_enforced_for_rules` fails which would need investigation.
> 
> /hold

The test fails because the rule file has been intentionally modified by prometheus-operator to avoid rule file name collision. 
This change is brought by [this commit](https://github.com/openshift/prometheus-operator/pull/141/commits/97d7df9ebbe1c93085c4f78c67697e70176b4f80).

I'm going to modify [the test](https://github.com/openshift/cluster-monitoring-operator/blob/4ecf1715bf3f572edb1c424cf3185f37719521fe/test/e2e/user_workload_monitoring_test.go#L733) `TestUserWorkloadMonitoringAlerting/assert_tenancy_model_is_enforced_for_rules` in CMO to reflect this change.

**Comment by raptorsun** [comment]
[A PR](https://github.com/openshift/cluster-monitoring-operator/pull/1479) has been created in CMO to fix the failing test TestUserWorkloadMonitoringAlerting.

**Comment by raptorsun** [comment]
Now updated to version 0.52.1.

**Pull request merged**
