### PR TITLE
Bump upstream

### PR DESCRIPTION
**Pull request by s-urbaniak**
As discussed in the engineering sync this bumps openshift/master to the current master state of upstream to be able to iterate on user workload monitoring.

/cc @LiliC @paulfantom @brancz @pgier

### CODE REVIEW

**Comment by s-urbaniak** [comment]
pleas re-lgtm, as I removed Max from the owners.

**Comment by s-urbaniak** [comment]
We have a valid e2e failure :-)
```
I1009 15:21:38.941350       1 operator.go:322] Updating ClusterOperator status to failed. Err: running task Updating Prometheus-k8s failed: reconciling Prometheus object failed: creating Prometheus object failed: Prometheus.monitoring.coreos.com "k8s" is invalid: spec.arbitraryFSAccessThroughSMs: Required value
E1009 15:21:38.949595       1 operator.go:267] Syncing "openshift-monitoring/cluster-monitoring-config" failed
E1009 15:21:38.949689       1 operator.go:268] sync "openshift-monitoring/cluster-monitoring-config" failed: running task Updating Prometheus-k8s failed: reconciling Prometheus object failed: creating Prometheus object failed: Prometheus.monitoring.coreos.com "k8s" is invalid: spec.arbitraryFSAccessThroughSMs: Required value
```

@paulfantom we should default `arbitraryFSAccessThroughSMs` to true, so we don't break existing installations.

**Comment by paulfantom** [comment]
`arbitraryFSAccessThroughSMs` is by default set to false (source: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#arbitraryfsaccessthroughsmsconfig) which means we are allowing filesystem access, which is what had previously. The problem here is that this field is now a required one, which I will change soon.

**Comment by s-urbaniak** [comment]
@paulfantom sounds good, thanks!

**Comment by s-urbaniak** [comment]
@LiliC @paulfantom please re-lgtm, let's also see what e2e says :)

**Pull request merged**
