### PR TITLE
Bug 1806541: Update prometheus-operator to 0.40.0

### PR DESCRIPTION
**Pull request by s-urbaniak**
/cc @openshift/openshift-team-monitoring

### CODE REVIEW

**Comment by s-urbaniak** [comment]
I am a bit lost here :thinking: 
```
error: some steps failed:
  * could not resolve inputs: could not determine inputs for step [input:ocp_4.0_base]: could not resolve base image: imagestreamtags.image.openshift.io "4.0" not found
time="2020-07-01T12:56:13Z" level=info msg="Reporting job state \"failed\" with reason \"resolving_inputs\""
```

**Comment by paulfantom** [comment]
/title Bug 1806541: Update prometheus-operator to 0.40.0

**Comment by paulfantom** [comment]
/retitle Bug 1806541: Update prometheus-operator to 0.40.0

**Comment by lilic** [comment]
🤞 :)

**Comment by simonpasquier** [comment]
/hold

From the [e2e-aws logs](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_prometheus-operator/77/pull-ci-openshift-prometheus-operator-master-e2e-aws/1278990202827706368/artifacts/e2e-aws/gather-extra/pods/openshift-monitoring_prometheus-operator-7bfb48567b-dw5x4_prometheus-operator.log), we need to manage the prometheus-operator's CRDs now:

```
flag provided but not defined: -manage-crds
Usage of /usr/bin/operator:
  -add_dir_header
    	If true, adds the file directory to the header
```

**Comment by paulfantom** [comment]
unholding as https://github.com/openshift/cluster-monitoring-operator/pull/843 is merged

/unhold
/retest

**Pull request merged**
