### PR TITLE
Bug 1801368: Bump v0.34.1

### PR DESCRIPTION
**Pull request by pgier**
Backport of #52

### CODE REVIEW

**Comment by eparis** [comment]
It seems this was a problem with kube 1.17.  Why are we making changes in 4.3?

**Comment by lilic** [comment]
@eparis At the time it was not clear which aspects of 1.17 were backported to 4.3.

**Comment by pgier** [comment]
This PR may have been overly proactive.  Feel free to close it, and we can create a new PR if the issue shows up in 4.3.

**Comment by sdodson** [comment]
@s-urbaniak @lilic @pgier What's the decision on whether this is moving forward or not?

**Comment by s-urbaniak** [comment]
closing out then as this issue indeed was showing up in 1.17, closing out the corresponding bugzilla too.

**Pull request closed without merging**
